name: ${project.name}
version: ${project.version}
description: ${project.description}
author: ${project.author}
website: ${project.url}
main: ${project.main}
softdepend: [Flags]
commands:
  tradeshop:
    description: Allows you to create and add trades to a TradeShop.
    permission: tradeshop.user
    usage: /tradeshop <create|add|admin>
    alisases: ts
permissions:
  tradeshop.user:
    description: Gives access to create a TradeShop.
    default: true
  tradeshop.admin:
    description: Allows a user access owner actions for any TradeShop chest.
    default: op
    children:
      tradeshop.user: true
